title: Catherine Gonzales # your name (or website title) here
logo: "Screen Shot 2023-03-23 at 3.35.32 PM.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | Data Driven Mathematics Educator | Problem Solver
  I am thrilled to begin the transition from education into data analytics. 
  I will post new projects periodically so feel free to follow along on my journey! 📈
   <br><br>
  <a href="https://www.linkedin.com/in/catherine-gonzales-012606269">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
